export const skillsList=[
   {
    id:1,
    icon:"vscode-icons:file-type-html",
    Label:"HTML"
   }, 
   {
    id:2,
    icon:"vscode-icons:file-type-css2",
    Label:"CSS"
   }, 
   {
    id:3,
    icon:"vscode-icons:file-type-js-official",
    Label:"Javascript"
   }, 
   {
    id:4,
    icon:"devicon:react",
    Label:"React"
   }, 
   {
    id:5,
    icon:"devicon:git",
    Label:"Git"
   }, 
   {
    id:6,
    icon:"mdi:github",
    Label:"GitHub"
   },
   {
    id:7,
    icon:"devicon:figma",
    Label:"Figma"
   }, 
   {
    id:8,
    icon:"devicon:tailwindcss",
    Label:"Tailwind"
   } 
   
]